Index compound parent object with data from children, and vice versa
discoverygarden/uol-basic-solr-config pull request #9
Opened 2019-03-11 13:07 UTC by IAMlKeno

2019-03-18 19:03 UTC, mghughes commented
Code looks good - guessing you didn't mean to change the file permissions on `foxmlToSolr.xslt` though?

2019-03-18 19:10 UTC, mghughes requested changes
Code looks good - guessing you didn't mean to change the file permissions on foxmlToSolr.xslt though?

2019-03-18 20:05 UTC, IAMlKeno commented
updated file permissions

2019-03-19 12:40 UTC, mghughes approved these changes

2019-03-19 12:40 UTC, merged